name: EMA CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    name: EMA CI
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make CC=gcc CXX=g++
